**N DIMENSIONAL ARRAY IN NUMPY**

In [ ]:
# n dimensional

import numpy as np
# 3d = [2d,2d,2d]
arr3d = np.random.randint(1,200,(5,10,5))
arr3d


array([[[168,  56,  48, 130,  96],
        [166,  35, 168,  19,  77],
        [ 51,  41,  57,  42, 143],
        [116, 173,  52, 121,  80],
        [ 76,  27, 184,  18,  50],
        [ 19,   2, 195, 138,  52],
        [168,  40,  27, 149, 196],
        [123,  37,  38, 117, 103],
        [186, 103, 193,  19, 136],
        [ 17, 188,  71,  65,  43]],

       [[ 37,  30,  70,  47,  30],
        [118, 153,  50,   5, 142],
        [ 92,  74,  43, 198,  52],
        [106,   7, 164,  63,  45],
        [103,  52,  42, 168,  72],
        [183, 130, 185,  78, 134],
        [ 68, 161,   3,  76, 177],
        [172,  91,  28, 164,  50],
        [113, 104, 179, 111, 162],
        [138,  86, 104, 127, 195]],

       [[115, 157, 133, 123, 112],
        [ 60, 172,  87, 191, 143],
        [122, 135,  29,  75, 186],
        [195, 184,  30, 162, 172],
        [  6, 172,  96, 133,  89],
        [ 13,  94,  36,   8, 129],
        [  2, 194, 116,  19,  38],
        [ 94,  91,  60,  98, 110],
        [ 52,  5

In [ ]:
arr3d.shape
#(5,10,5)
# 5==> table
# 10==> rows
# 5==> coulumns
# arr3d=[table , rows , columns]
# arr3d=[st:sp:j,st:sp:j,st:sp:j]

(5, 10, 5)

In [ ]:
arr3d.ndim

3

In [ ]:
arr3d[0:2]   #table denotions [0-4]
arr3d[4]                #poitive indexing
arr3d[-1]                        #negative indexing

array([[118,  38, 152, 120,  32],
       [ 52,  43,  93, 135, 192],
       [ 32, 168, 156, 164, 125],
       [ 26,  60, 175,  78,  91],
       [176,  25, 115,  42,  50],
       [197,   5, 109, 102,  56],
       [112,  62, 122,  83,  34],
       [135,  96, 191,  25, 189],
       [144,  40, 184, 127,  61],
       [ 43,  94,  69,  48, 108]])

In [ ]:
arr3d[0:5,6:]
arr3d[0:,9:]
arr3d[0:5,9:,4:]=500
arr3d


array([[[168,  56,  48, 130,  96],
        [166,  35, 168,  19,  77],
        [ 51,  41,  57,  42, 143],
        [116, 173,  52, 121,  80],
        [ 76,  27, 184,  18,  50],
        [ 19,   2, 195, 138,  52],
        [168,  40,  27, 149, 196],
        [123,  37,  38, 117, 103],
        [186, 103, 193,  19, 136],
        [ 17, 188,  71,  65, 500]],

       [[ 37,  30,  70,  47,  30],
        [118, 153,  50,   5, 142],
        [ 92,  74,  43, 198,  52],
        [106,   7, 164,  63,  45],
        [103,  52,  42, 168,  72],
        [183, 130, 185,  78, 134],
        [ 68, 161,   3,  76, 177],
        [172,  91,  28, 164,  50],
        [113, 104, 179, 111, 162],
        [138,  86, 104, 127, 500]],

       [[115, 157, 133, 123, 112],
        [ 60, 172,  87, 191, 143],
        [122, 135,  29,  75, 186],
        [195, 184,  30, 162, 172],
        [  6, 172,  96, 133,  89],
        [ 13,  94,  36,   8, 129],
        [  2, 194, 116,  19,  38],
        [ 94,  91,  60,  98, 110],
        [ 52,  5

In [ ]:
arr = np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
arr.reshape(20,3)                   # 2 d      (20,3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [ ]:
arr = arr.reshape(2,15,2)
arr                  # 3 d      ()

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39],
        [40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]]])

In [ ]:
arr2 = arr.ravel()
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
arr =np.random.randint(1,200,(5,3))
arr

array([[ 66, 133, 115],
       [ 15, 176, 165],
       [116,  52, 159],
       [115,  18,  62],
       [ 55,  25, 175]])

In [ ]:
arr.shape

(5, 3)

***TRANSPOSE TERM***

In [ ]:
np.transpose(arr).shape

(3, 5)

In [ ]:
arr.T

array([[ 26, 147,  72,  13, 117],
       [ 36,  70, 115, 147, 146],
       [194,  74,  14,  55, 182]])

In [ ]:
arr2=arr.ravel()
arr2

array([ 26,  36, 194, 147,  70,  74,  72, 115,  14,  13, 147,  55, 117,
       146, 182])

In [ ]:
arr2.max()                 #max value
arr2.min()                   #min value
arr2.mean()

93.86666666666666

In [ ]:
np.median(arr2)

74.0

In [ ]:
arr = np.array([9,7,8])
arr

array([9, 7, 8])

**wriiten index value of minimum**

In [ ]:
arr.argmin()

1

**Written index value max**

In [ ]:
arr.argmax()

0

In [ ]:
arr.sort()                  #ascending
arr

array([7, 8, 9])

In [ ]:
arr[::-1]                         #descending

array([9, 8, 7])

In [ ]:
arr.argsort()          #  (7,8,9)   condition   index value

array([1, 2, 0])

In [ ]:
#QUIZ

arr = np.random.randint(1,300,500)
arr
count=0
for item in arr:
  if item >=50  and item <=150:
    count+=1
    print(item)
print("no.of item",count)


57
149
84
89
68
120
130
73
121
56
92
136
105
58
82
135
59
69
150
83
81
145
64
70
52
71
101
83
130
67
82
131
52
127
146
74
141
90
93
127
142
121
105
134
76
138
78
59
82
90
60
104
87
76
138
87
90
78
92
103
73
73
51
76
66
110
78
52
60
116
120
110
115
85
107
94
138
143
55
141
135
64
113
55
134
89
143
145
118
94
64
89
108
125
128
144
122
72
127
85
112
146
141
149
56
92
86
130
80
145
67
122
91
110
121
120
90
144
130
97
68
60
80
89
150
117
112
117
110
142
59
132
86
91
136
122
61
128
58
81
62
91
131
92
92
94
125
88
135
112
116
52
67
145
119
50
88
80
67
81
138
120
114
133
124
113
127
141
119
101
62
81
96
74
no.of item 174


149.672

In [ ]:
arr.mean()
np.median(arr)

147.5