**NUMPY LIBRARY**

In [ ]:
import numpy as np
print ("numpy imported")

numpy imported


**ARRAY CREATION**

In [ ]:
ls=[25,14,78,98,78,56,666]
arr = np.array(ls)
arr


array([ 25,  14,  78,  98,  78,  56, 666])

**nd === n dimensional array**

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
ls=[24,"upflairs",34.3,True]
ls

[24, 'upflairs', 34.3, True]

i**f in list one element is float than it create whole element as a float value**

In [ ]:
ls = [23,34,89,745,64,102,78,64,1000.56]
arr = np.array(ls)
arr

array([  23.  ,   34.  ,   89.  ,  745.  ,   64.  ,  102.  ,   78.  ,
         64.  , 1000.56])

**if in list one element is string than it create whole element as a string value**

In [ ]:
ls = [23,34,89,745,64,102,78,64,100,"upflairs"]
arr=np.array(ls)
arr

array(['23', '34', '89', '745', '64', '102', '78', '64', '100',
       'upflairs'], dtype='<U21')

**to find the lenght and size of array or list**

In [ ]:
ls=[25,14,78,98,78,56,666]
arr = np.array(ls)
arr
len(arr)
arr.size

7

In [ ]:
arr.dtype  #datatype of array

dtype('int64')

In [ ]:
arr[1:]                    #starting and ending point od array

array([ 14,  78,  98,  78,  56, 666])

In [ ]:
arr[-3:]

array([ 78,  56, 666])

In [ ]:
arr[4:]

array([ 78,  56, 666])

In [ ]:
arr[::1]

array([ 25,  14,  78,  98,  78,  56, 666])

In [ ]:
np.arange(1,60)                 #to create array without any written practice

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
arr2=np.arange(45)                 #without any starting point
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [ ]:
arr2=np.arange(0,145,3)                #range (start,stop,jump)
arr2

array([  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
        39,  42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,
        78,  81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114,
       117, 120, 123, 126, 129, 132, 135, 138, 141, 144])

In [ ]:
len (arr2)

49

In [ ]:
np.ones(10)                #to make output same as multiple times

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.zeros(23)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [ ]:
np.linspace(1,145,18)

array([  1.        ,   9.47058824,  17.94117647,  26.41176471,
        34.88235294,  43.35294118,  51.82352941,  60.29411765,
        68.76470588,  77.23529412,  85.70588235,  94.17647059,
       102.64705882, 111.11764706, 119.58823529, 128.05882353,
       136.52941176, 145.        ])

In [ ]:
arr = np.random.randint(1,300,560)
arr

array([194, 212, 299, 269, 243,  81, 208, 262, 175, 108,  77, 163,  72,
       160,  30, 217, 175, 112,  75,  55, 192, 267, 155, 286,   5, 292,
        86, 115,  12,  62, 278, 235, 270, 104, 221,  33,  62, 101, 102,
       106, 122,  81,  24, 224, 298, 298,  91,  32, 214, 213, 262, 136,
         8, 153,  85, 149, 128, 126, 239,  72,  91,  47, 107, 238,  28,
       110,  19, 250, 204, 205, 200,  43, 117, 115, 183, 274, 131,  49,
       118,  11, 227, 125, 115, 100, 155, 165, 280, 148, 259, 158, 101,
       296, 269, 139, 163, 227, 208,  44,  55,  58, 183, 237, 106, 147,
        32, 141, 248,  94, 128, 295, 238, 121, 190, 126,  58, 218,  54,
       182, 183, 113, 150, 278, 208, 196, 157, 298, 177,  68, 285, 292,
       249, 299, 221, 276,  71,  55,  89,  65, 211, 178,  43, 114,  79,
       122, 275, 114,  52, 181,  58, 235,  78,  48, 126, 266,  50,   1,
        46, 142, 194, 113, 275, 180, 281,  73, 290, 125,  87, 172, 174,
       127, 260, 196,  19, 155, 192, 159, 289, 297, 254, 105, 15

In [ ]:
arr.size

560

In [ ]:
count=0
for item in arr:
  if item <=89:
      count+=1
      print(item)
print("no. of item",count)


81
77
72
30
75
55
5
86
12
62
33
62
81
24
32
8
85
72
47
28
19
43
49
11
44
55
58
32
58
54
68
71
55
89
65
43
79
52
58
78
48
50
1
46
73
87
19
4
72
50
39
50
82
39
44
46
55
89
45
18
39
72
8
84
22
37
43
22
20
68
40
72
38
35
31
83
61
27
61
26
70
81
14
51
41
28
4
57
18
36
89
46
75
59
37
81
65
44
86
83
40
2
87
40
70
73
71
32
48
24
3
35
31
78
72
88
12
13
13
52
14
63
15
81
7
25
83
52
7
15
69
51
3
86
14
55
56
58
89
24
36
33
82
40
70
71
11
49
39
11
12
82
22
48
49
21
89
51
84
79
85
8
55
72
75
11
80
no. of item 167


In [ ]:
arr[arr<=56]

array([30, 55,  5, 12, 33, 24, 32,  8, 47, 28, 19, 43, 49, 11, 44, 55, 32,
       54, 55, 43, 52, 48, 50,  1, 46, 19,  4, 50, 39, 50, 39, 44, 46, 55,
       45, 18, 39,  8, 22, 37, 43, 22, 20, 40, 38, 35, 31, 27, 26, 14, 51,
       41, 28,  4, 18, 36, 46, 37, 44, 40,  2, 40, 32, 48, 24,  3, 35, 31,
       12, 13, 13, 52, 14, 15,  7, 25, 52,  7, 15, 51,  3, 14, 55, 56, 24,
       36, 33, 40, 11, 49, 39, 11, 12, 22, 48, 49, 21, 51,  8, 55, 11])

In [ ]:
arr[arr<=56].size

101

In [ ]:
arr.ndim          #n dimensional array

1

**2-Dimensional array in numpy**

In [ ]:
#        <<<<<<<<<<<<<    2 D ARRAY >>>>>>>>>>>>>>>>>>>>

arr

array([ 25,  14,  78,  98,  78,  56, 666])

In [ ]:
#2d [1d,1d,1d,1d]

lst=[[1,2,3,],[4,5,6],[7,8,9]]
type(lst)

list

In [ ]:
import numpy as np

In [ ]:
arr=np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape                # row and columns

(3, 3)

In [ ]:
arr.ndim

2

In [ ]:
arr[0]                                 #single row
arr[:2]                                 #multiple row

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr[1:3,1:3]

array([[5, 6],
       [8, 9]])

**random creation array in numpy**

In [ ]:
arr2 = np.random.randint(1,200,(10,6))
arr2
# arr2[4:]
# arr2[4:9,3:]
# arr2[-6:-1,-3:]
arr2[-6:-4,-6:-4]
# arr2[-1,-1] =  1000
# arr2[-1,-1]
# arr2
# arr2[-10,-3] =  500
arr2[0][3] = 4000
arr2[0,3]
arr2

array([[  39,  114,  105, 4000,  162,  184],
       [  48,  146,   46,  193,  123,  132],
       [  37,   13,   60,  107,  139,  118],
       [  18,  105,   66,   74,   23,   37],
       [ 165,  131,  190,  169,  179,   52],
       [ 137,  120,  113,  127,  189,   34],
       [  29,   58,    6,  194,  119,  129],
       [ 188,  109,  196,   32,  114,   71],
       [ 166,  118,  134,   30,  161,   61],
       [  78,   87,  112,  199,  168,  149]])